/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExhibitRouteImport } from './routes/exhibit'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyTicketNumberRouteImport } from './routes/verify.$ticketNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhibitRoute = ExhibitRouteImport.update({
  id: '/exhibit',
  path: '/exhibit',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyTicketNumberRoute = VerifyTicketNumberRouteImport.update({
  id: '/verify/$ticketNumber',
  path: '/verify/$ticketNumber',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exhibit': typeof ExhibitRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/verify/$ticketNumber': typeof VerifyTicketNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exhibit': typeof ExhibitRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/verify/$ticketNumber': typeof VerifyTicketNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exhibit': typeof ExhibitRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/verify/$ticketNumber': typeof VerifyTicketNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/exhibit' | '/register' | '/terms' | '/verify/$ticketNumber'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/exhibit' | '/register' | '/terms' | '/verify/$ticketNumber'
  id:
    | '__root__'
    | '/'
    | '/exhibit'
    | '/register'
    | '/terms'
    | '/verify/$ticketNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExhibitRoute: typeof ExhibitRoute
  RegisterRoute: typeof RegisterRoute
  TermsRoute: typeof TermsRoute
  VerifyTicketNumberRoute: typeof VerifyTicketNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhibit': {
      id: '/exhibit'
      path: '/exhibit'
      fullPath: '/exhibit'
      preLoaderRoute: typeof ExhibitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$ticketNumber': {
      id: '/verify/$ticketNumber'
      path: '/verify/$ticketNumber'
      fullPath: '/verify/$ticketNumber'
      preLoaderRoute: typeof VerifyTicketNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExhibitRoute: ExhibitRoute,
  RegisterRoute: RegisterRoute,
  TermsRoute: TermsRoute,
  VerifyTicketNumberRoute: VerifyTicketNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
